# Generated by Django 2.2 on 2019-07-20 02:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0003_auto_20190708_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readdetail',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 7, 20, 2, 51, 49, 17315, tzinfo=utc)),
        ),
    ]
