# Generated by Django 2.2 on 2019-07-20 08:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0004_auto_20190720_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readdetail',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 7, 20, 8, 30, 52, 779592, tzinfo=utc)),
        ),
    ]
