# Generated by Django 2.2 on 2019-07-20 08:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0005_auto_20190720_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readdetail',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 7, 20, 8, 38, 49, 517507, tzinfo=utc)),
        ),
    ]
